#!/bin/bash
IP_SERVER='192.168.10.5'
PASSWORD_SERVER='thanh123'
IP_ILO='192.168.10.6'
PASSWORD_ILO='thanh123'

# Shutdown network via ssh
fping -u $IP_SERVER >& /dev/null
if [ $? -eq 0 ]
then
    echo "sshpass -p ${PASSWORD_SERVER} ssh -o StrictHostKeyChecking=no root@${IP_SERVER} 'systemctl stop network;' 2> /dev/null"
fi

# Shutdown ilo via ilo's ssh
echo "sshpass -p ${PASSWORD_ILO} ssh -o StrictHostKeyChecking=no admin@${IP_ILO} 'power off'"